### ISSUE TITLE
update documentation @ task_getting_started_customers.adoc

### ISSUE THREAD

**Issue by HemanthaSKota** [NetAppDocs/converged-systems-advisor#22]
update documentation @ https://github.com/NetAppDocs/converged-systems-advisor/blob/master/task_getting_started_customers.adoc

From
You must setup a read-only account in cisco ucs manager and on cisco nexus switches.
An admin account is required for ONTAP collect configuration data from each device

To
You must set up a read-only account in Cisco UCS Manager and on your Cisco Nexus switches. An admin account is required for ONTAP system and VMWARE vCenter device. The agent uses these accounts to collect configuration data from each device.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  I will be working to validate this change.

**Comment by netapp-aherbin** [comment]
These changes have been implemented
