### ISSUE TITLE
ifdown command is not available

### ISSUE THREAD

**Issue by amkirk** [NetAppDocs/converged-systems-advisor#23]
Page: [Setting a static IP address on the agent](https://docs.netapp.com/us-en/converged-systems-advisor/task_setting_static_ip.html)

When I try to run the ifdown command, I see command not found.

**Comment by netapp-aherbin** [comment]
Thank you for your comment.  I am following up with our Engineering team.

**Comment by netapp-aherbin** [comment]
The correct command is:
# /sbin/ifdown eth0

This has been updated in the documentation.
